[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "./styles/tailwind.css",
    "-o",
    "./styles/main.css",
]
